export const GET_ORDEN_ESTADOS = "GET_ORDEN_ESTADOS";
export const GET_ORDEN_BY_TITLE = "GET_ORDEN_BY_TITLE";
export const GET_JOBS_POSTING = "GET_JOBS_POSTING";
export const GET_JOB_POSTING_DETAIL = "GET_JOB_POSTING_DETAIL";