export const GET_PERSONAS = "GET_PERSONAS";
export const DELETE_PERSONA = "DELETE_PERSONA";
export const GET_PEOPLE_DETAIL = "GET_PEOPLE_DETAIL";
export const GET_PEOPLE_BY_NAME = "GET_PEOPLE_BY_NAME";
export const ORDER_BY_FIRST_NAME = "ORDER_BY_FIRST_NAME"